blank_issues_enabled: false
contact_links:
  - name: kaboo-workflows Discussions
    url: https://github.com/gl-pgege/kaboo-workflows/discussions
    about: Please ask and answer questions here
  - name: kaboo-workflows Documentation
    url: https://gl-pgege.github.io/kaboo-workflows/
    about: Visit the documentation for help
